apiVersion: v1
kind: Service
metadata:
  name: echochain-validator-headless
  namespace: echochain
  labels:
    app: echochain-node
    component: validator
    tier: blockchain
spec:
  clusterIP: None
  ports:
  - name: p2p
    port: 30333
    targetPort: 30333
    protocol: TCP
  - name: rpc
    port: 9933
    targetPort: 9933
    protocol: TCP
  - name: ws
    port: 9944
    targetPort: 9944
    protocol: TCP
  - name: prometheus
    port: 9615
    targetPort: 9615
    protocol: TCP
  selector:
    app: echochain-node
    component: validator
---
apiVersion: v1
kind: Service
metadata:
  name: echochain-rpc
  namespace: echochain
  labels:
    app: echochain-node
    component: rpc
    tier: blockchain
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  ports:
  - name: rpc
    port: 9933
    targetPort: 9933
    protocol: TCP
  - name: ws
    port: 9944
    targetPort: 9944
    protocol: TCP
  selector:
    app: echochain-node
    component: validator
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600
---
apiVersion: v1
kind: Service
metadata:
  name: echochain-p2p
  namespace: echochain
  labels:
    app: echochain-node
    component: p2p
    tier: blockchain
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - name: p2p
    port: 30333
    targetPort: 30333
    protocol: TCP
  selector:
    app: echochain-node
    component: validator
---
apiVersion: v1
kind: Service
metadata:
  name: echochain-metrics
  namespace: echochain
  labels:
    app: echochain-node
    component: metrics
    tier: blockchain
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9615
    targetPort: 9615
    protocol: TCP
  selector:
    app: echochain-node
    component: validator